package game.constants;

import lombok.Getter;

public enum MessageKey {
    RACING_CARS_INPUT_DELIMITER("RACING_CARS_INPUT_DELIMITER"),
    RACING_CARS_INPUT_DELIMITER_NAME("RACING_CARS_INPUT_DELIMITER_NAME"),
    RACING_CARS_INPUT_PROMPT_FORMAT("RACING_CARS_INPUT_PROMPT_FORMAT"),
    TOTAL_TRY_COUNT_INPUT_PROMPT_FORMAT("TOTAL_TRY_COUNT_INPUT_PROMPT_FORMAT"),
    EXCEPTION_FORMAT("EXCEPTION_FORMAT"),
    RACING_CAR_INVALID_NAME_EXCEPTION_FORMAT("RACING_CAR_INVALID_NAME_EXCEPTION_FORMAT"),
    RACING_GAME_NOT_COMPLETED_EXCEPTION_FORMAT("RACING_GAME_NOT_COMPLETED_EXCEPTION_FORMAT"),
    RACING_GAME_INVALID_EXCEPTION_FORMAT("RACING_GAME_INVALID_EXCEPTION_FORMAT");

    MessageKey(String key) {
        this.key = key;
    }

    @Getter
    private String key;
}
